aws-region        = "eu-west-2"
aws-profile       = "economist-ds-dev"
user-data-script  = "./scripts/spinup.sh"
instance-ami      = "ami-01419b804382064e4"
instance-key-name = "engagement-paris.pem"
instance-tag-name = "Advanced-example-test-instance"
iam-role-name     = "engagement-ec2-role"