aws-region  = "eu-west-3"
aws-profile = "economist-ds-dev"
instance-tag-name = "Test-multi-docker"
instance-type = "m5.xlarge"
user-data-script  = "./user-data.sh"
instance-ami    = "ami-0dd7e7ed60da8fb83"
instance-key-name = "engagement-paris"
